### ISSUE TITLE
Can I make an App using API?

### ISSUE THREAD

**Issue by ChangJoo-Park** [Tahul/journapi#9]
Hello @Tahul ! 

I found journapi on ProductHunt and your API docs.

Can I make an app using your API?

I made it today here.

## Authorization

![Screenshot_1614329720](https://user-images.githubusercontent.com/1451365/109278399-d5d81f80-785b-11eb-892a-5fe3a698fd59.png)

## Listing

![image](https://user-images.githubusercontent.com/1451365/109278680-2485b980-785c-11eb-9698-a7c242f87c66.png)

## Editing

![image](https://user-images.githubusercontent.com/1451365/109278702-2ea7b800-785c-11eb-81d3-ebd93dace3f7.png)

I use all your assets. so I need your accept it goes on.

## Job to do

- [ ] Animation on collapse,
- [ ] Animating Logo like https://journapi.app/

**Comment by ChangJoo-Park** [comment]
I send you for internal sharing for Android :)

**Comment by Tahul** [comment]
Hey,

This it totally open source, please go on 👍 

I would love being credited somewhere if you plan on making this public though, I made it open source so people can self-host it and use it themselves.

Have fun playing with it, and tell me if you find bugs!

**Comment by ChangJoo-Park** [comment]
Thanks @Tahul  :) 
I make my repo to public now. https://github.com/ChangJoo-Park/journapi_flutter
It would be nice if there were a little more features, but now I have proceeded with what I have
